Python for Data Science Practical

#Name : JAY Prajapati
#Roll No : 028
Date Of Practical : 05-08-2026


**A. Write a python code to create Numpy Array**.

In [3]:
import numpy as np
a = np.array([1,2,3])
print(a)

[1 2 3]


**B. Write a python code to demonstrate basic operations on single array.**

In [4]:
print(a+2)
print(a*2)

[3 4 5]
[2 4 6]


**C. Write a python code to create array with 10 elements and slice element from 1st to 5th element.**

In [5]:
b = np.array([1,2,3,4,5,6,7,8,9,10])
print(b[1:5])

[2 3 4 5]


**D.Write a python code to sort an array alphabetically.**

In [6]:
Name =(["JAY","Amit","Ramesh","Raj","Vijay"])
print(np.sort(Name))

['Amit' 'JAY' 'Raj' 'Ramesh' 'Vijay']


**E. Write a python code to create a filter array that will return maximum values from an array.**

In [9]:
price = np.array([10000,25000,15000,40000,55000])
print(price[price>4000])

[10000 25000 15000 40000 55000]
